package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Check that the page is opened")
    void generatedTest() {
        step("Open https://intourist.ru/search/", () -> {
            step("// todo: just add selenium action");
        });

        step("Set departure as MRV", () -> {
            step("// todo: just add selenium action");
        });

        step("Set destination as Turkey", () -> {
            step("// todo: just add selenium action");
        });

        step("Search", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify that the list of hotels is displayed", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://intourist.ru/search/'", () ->
            open("https://intourist.ru/search/"));

        step("Page title should have text 'Intourist online бронирование'", () -> {
            String expectedTitle = "Intourist online бронирование";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://intourist.ru/search/'", () ->
            open("https://intourist.ru/search/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}